### ISSUE TITLE
Adding a reference to Microsoft.DotNet.ILCompiler 8.0 preview to no-runtime project results in no console output

### ISSUE THREAD

**Issue by Michael-Kelley** [MichalStrehovsky/zerosharp#44]
I want to use the preview version of NativeAot in order to make use of the new `UnmanagedEntryPointsAssembly` MSBuild property, but this results in no console output when invoking `WriteConsoleW`.

<br>

**Reproduction steps:**
* Add the following to the `no-runtime` project file:
```xml
<ItemGroup>
	<PackageReference Include="Microsoft.DotNet.ILCompiler; runtime.win-x64.microsoft.dotnet.ilcompiler" Version="8.0.0-preview.4.23207.2" />
</ItemGroup>
```
* Run `dotnet publish -r win-x64 -c Debug` in a command prompt.
* Run the resulting `no-runtime.exe` file from the publish directory.

<br>

**Expected result:**
Console should display `Hello world!`.

<br>

**Observed result:**
Console displays no text and no errors.

**Comment by Wenveo** [comment]
I had a similar issue today when compiling with ILC, but it seems to be related to `strings`. I also couldn't display the content and title correctly when I tried `MessageBoxW`.

I later removed the `--dehydrate` argument and the string output worked.

![image](https://user-images.githubusercontent.com/62750690/230647086-b7173282-2aba-4f15-8804-e77f34ab283a.png)
![image](https://user-images.githubusercontent.com/62750690/230647352-b34ed441-c3a6-44fc-84db-4126c9efe2ed.png)

Or add the prop `<IlcDehydrate>false</IlcDehydrate>` to your project.
Hope it is useful to you.😄

**Comment by Michael-Kelley** [comment]
That did the trick. Thanks! I assume dehydration affects the memory layout of the string and that this is what is causing it to fail with dehydration enabled?

**Comment by Wenveo** [comment]
> I assume dehydration affects the memory layout of the string and that this is what is causing it to fail with dehydration enabled?

Because the dehydrated data is only supported at runtime.

When "Dehydrate" is enabled (which is enabled by default in .NET 8 Aot), the runtime data structures are dehydrate encoded and later dehydrate decoded in [Bootstrap/main.cpp](https://github.com/dotnet/runtime/blob/1b22d373f2cdb08ad05ac79019fab52dc795f6fe/src/coreclr/nativeaot/Bootstrap/main.cpp#L170-L182) (and this [StartupCodeHelpers.cs -> RehydrateData](https://github.com/dotnet/runtime/blob/e3a80f31d0eb629cf9ce8a6153bd0bd3fed877d3/src/coreclr/nativeaot/Common/src/Internal/Runtime/CompilerHelpers/StartupCodeHelpers.cs#L98-L103)).

If you remove the runtime of your app, it will not be able to decode the dehydrated data at startup...

See more:
- https://github.com/dotnet/runtime/pull/77884
- [Internal.Runtime.DehydratedData.cs](https://github.com/dotnet/runtime/blob/e3f55cbfd83162bc85d73d69c765e7f44c478e6d/src/coreclr/tools/Common/Internal/Runtime/DehydratedData.cs)
